repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
        language_version: python3.10
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        always_run: true

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--target-version, py310]
        files: ^api/src/.*\.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests]
        files: ^api/.*\.py$

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
    -   id: python-safety-dependencies-check

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        types: [python]
        args: [--config=api/pyproject.toml]
        files: ^api/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        files: ^api/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^web/.*\.(ts|tsx|js|css|html|json)$
        args:
          ["--config=web/.prettierrc.js", "--ignore-path=web/.prettierignore"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: ^api/src/.*\.py$
        args: [ '--max-line-length=119', '--max-complexity=18', '--select=B,C,E,F,W,T4,B9', '--ignore=E203,E266,E501,W503' ]

  - repo: local
    hooks:
      - id: mypy
        name: Python type checking
        pass_filenames: false
        files: ^api/.*\.py$
        entry: sh -c "api/.venv/bin/python -m mypy --namespace-packages --ignore-missing-imports api/src/app.py"
        language: system

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: sh -c "export PYTHONPATH=./src && api/.venv/bin/python -m pytest api/src/tests"
        language: system
        pass_filenames: false
        always_run: true
