version: "3.8"

services:

  api:
    build:
      target: development
    image: template-api-dev
    volumes:
      - ./api/src/:/code
    environment:
      ENVIRONMENT: local
      LOGGING_LEVEL: debug
      MONGODB_DATABASE: $MONGODB_DATABASE
      MONGODB_USERNAME: $MONGODB_USERNAME
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      MONGODB_HOSTNAME: db
      MONGODB_PORT: $MONGODB_PORT
      OAUTH_TOKEN_ENDPOINT: $OAUTH_TOKEN_ENDPOINT
      OAUTH_AUTH_ENDPOINT: $OAUTH_AUTH_ENDPOINT
      OAUTH_WELL_KNOWN: $OAUTH_WELL_KNOWN
      OAUTH_AUDIENCE: $OAUTH_AUDIENCE
      SECRET_KEY: $SECRET_KEY
    ports:
      - "5000:5000"

  web:
    build:
      target: development
      args:
        AUTH_ENABLED: $AUTH_ENABLED
        AUTH_SCOPE: $AUTH_SCOPE
        CLIENT_ID: $CLIENT_ID
        TENANT_ID: $TENANT_ID
    image: template-web-dev
    stdin_open: true
    volumes:
      - ./web/src:/code/src
    environment:
      - NODE_ENV=development

  db:
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD