version: "3.8"

services:
  api:
    image: development
    build:
      context: .
      target: development
    environment:
      ENVIRONMENT: local
      MONGO_INITDB_ROOT_PASSWORD: maf
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs=
      AUTH_ENABLED: "False"

  db:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: maf


