name: "On push to branches"
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  generate-changelog:
    needs: tests
    uses: ./.github/workflows/generate-changelog.yaml

  docs:
    needs: generate-changelog
    uses: ./.github/workflows/publish-docs.yaml
    with:
      message: 'Warning: This is the development version.'
