name: "Test"
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:
    secrets:
      CR_SECRET:
        description: 'Secret to authenticate if using an other container registry than Github'
        required: false

env:
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_USER: $GITHUB_ACTOR
  API_IMAGE: ghcr.io/equinor/template-fastapi-react/api
  WEB_IMAGE: ghcr.io/equinor/template-fastapi-react/web

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build API image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REGISTRY -u $GITHUB_ACTOR --password-stdin
          docker pull $API_IMAGE
          docker build --target development --tag api-development ./api # TODO: --cache-from $API_IMAGE

      - name: BDD Integration tests
        if: ${{ false }}  # disable for now
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api behave

      - name: Pytest Integration tests
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm api pytest --integration

  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build Web Image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REGISTRY -u $GITHUB_ACTOR --password-stdin
          docker pull $WEB_IMAGE
          docker build --cache-from $WEB_IMAGE --target development --tag web-dev ./web
