on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:


jobs:
  common-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Check JSON
        run: pre-commit run check-json --all-files

      - name: Check YAML
        run: pre-commit run check-yaml --all-files

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Check valid Python files
        run: pre-commit run check-ast --all-files

      - name: Build API test image
        run: docker build --target development --tag api-development ./api

      - name: Black Linting
        run: docker run --rm api-development black --check --diff --exclude something .

      - name: Bandit Static Code Security Analysis
        run: docker run --rm api-development bandit --recursive . --exclude ./tests

      - name: Safety - Dependencies CVE Check
        run: docker run --rm api-development safety check

      - name: API Unit Tests
        run: docker run --rm api-development pytest tests

      - name: Documentation Check
        run: docker run --rm api-development interrogate

  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Precommit
        run: pip install pre-commit

      - name: Run prettier formatting
        run: pre-commit run prettier --all-files

      - name: Build Web test image
        run: docker build --target development --tag web-development ./web



