yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: pnp

# Fixes styled components error, see https://github.com/styled-components/styled-components/issues/3747
enableScripts: false

packageExtensions:
  "eslint-plugin-flowtype@*":
      dependencies:
       "@babel/plugin-syntax-flow": "*"
       "@babel/plugin-transform-react-jsx": "*"

  "@babel/plugin-syntax-flow@*":
      dependencies:
        "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
      dependencies:
        "@babel/core": "*"

  "fork-ts-checker-webpack-plugin@*":
     dependencies:
       "typescript": "*"
       "webpack": "*"

  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"

  "@testing-library/react@*":
     dependencies:
       "react": "*"
       "react-dom": "*"

  "styled-components@*":
    dependencies:
      react-is: "*"